export {default as Products} from './Product'
export {default as Categories} from './Categories'
export {default as Wishlist} from './Wishlist'
export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Profile} from './Profile'
export {default as Cart} from './Cart'